name: Master Workflow
on:
  push:
    branches:
      - master
jobs:
  runs-on: ubuntu-latest
  display-python-version:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
    job_2:
      needs: job_1
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
