name: Master Workflow
on:
  push:
    branches:
      - master
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  job_2:
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
